package com.crossover.spring.model;
// Generated 15/11/2016 06:08:45 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Parameter generated by hbm2java
 */
@Entity
@Table(name = "PARAMETER")
public class Parameter implements java.io.Serializable {

	@EmbeddedId
	@AttributeOverrides({
	@AttributeOverride(name = "parameterName", column = @Column(name = "parameter_name", nullable = false, length = 50)),
	@AttributeOverride(name = "parameterId", column = @Column(name = "parameter_id", nullable = false, length = 45)) })
	private ParameterId id;
	
	@Column(name = "parameter_varchar", length = 500)
	private String parameterVarchar;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "parameter_date", length = 19)
	private Date parameterDate;
	
	@Column(name = "parameter_int")
	private Integer parameterInt;
	
	@Column(name = "parameter_double", precision = 11)
	private Double parameterDouble;

	public Parameter() {
	}

	public Parameter(ParameterId id) {
		this.id = id;
	}

	public Parameter(ParameterId id, String parameterVarchar, Date parameterDate, Integer parameterInt,
			Double parameterDouble) {
		this.id = id;
		this.parameterVarchar = parameterVarchar;
		this.parameterDate = parameterDate;
		this.parameterInt = parameterInt;
		this.parameterDouble = parameterDouble;
	}

	public ParameterId getId() {
		return this.id;
	}

	public void setId(ParameterId id) {
		this.id = id;
	}

	public String getParameterVarchar() {
		return this.parameterVarchar;
	}

	public void setParameterVarchar(String parameterVarchar) {
		this.parameterVarchar = parameterVarchar;
	}

	public Date getParameterDate() {
		return this.parameterDate;
	}

	public void setParameterDate(Date parameterDate) {
		this.parameterDate = parameterDate;
	}

	public Integer getParameterInt() {
		return this.parameterInt;
	}

	public void setParameterInt(Integer parameterInt) {
		this.parameterInt = parameterInt;
	}

	public Double getParameterDouble() {
		return this.parameterDouble;
	}

	public void setParameterDouble(Double parameterDouble) {
		this.parameterDouble = parameterDouble;
	}

}
