package com.crossover.spring.model;
// Generated 15/11/2016 01:28:25 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "USERS")
public class User implements java.io.Serializable {

	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer id;
	
	@Column(name = "userid", unique = true, nullable = false, length = 32)
	private String userid;
	
	@Column(name = "password", nullable = false, length = 32)
	private String password;
	
	@Column(name = "name", length = 32)
	private String name;
	
	@Column(name = "email", length = 32)
	private String email;
	
	@Column(name = "active_flg")
	private Boolean activeFlg;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", nullable = false, length = 10)
	private Date createDate;
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_datetime", length = 19)
	private Date updateDatetime;

	public User() {
	}

	public User(String userid, String password, Date createDate) {
		this.userid = userid;
		this.password = password;
		this.createDate = createDate;
	}

	public User(String userid, String password, String name, String email, Boolean activeFlg, Date createDate,
			Date updateDatetime) {
		this.userid = userid;
		this.password = password;
		this.name = name;
		this.email = email;
		this.activeFlg = activeFlg;
		this.createDate = createDate;
		this.updateDatetime = updateDatetime;
	}

	
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUserid() {
		return this.userid;
	}

	public void setUserid(String userid) {
		this.userid = userid;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Boolean getActiveFlg() {
		return this.activeFlg;
	}

	public void setActiveFlg(Boolean activeFlg) {
		this.activeFlg = activeFlg;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDatetime() {
		return this.updateDatetime;
	}

	public void setUpdateDatetime(Date updateDatetime) {
		this.updateDatetime = updateDatetime;
	}

}
